module.exports = {
  landing : '/',
  sendValidationEmail : '/valider-email',
  validationEmailSent: '/email-de-validation-envoye',
  createConf : '/creer-conf',
  confCreated : '/conf-creee',
  legalNotice : '/mentions-legales',
  showConf : '/conferences/:id',
  cancelConf : '/conferences/:id/annuler',
  stats: '/stats',
  contact: '/contact',
  faq: '/questions-frequentes',
  participantAction: '/dashboard/:token/:participantId/:action',
  dashboard: '/dashboard/:token',
  status: '/api/status',
}
